### PR TITLE
fix schemas

### PR DESCRIPTION
**Pull request by nezred**
the schemas had various differences, with the type signatures of the resolvers, so ive been trying to fix those.

for the moment i will publish this as a draft, and later we can think on how to get it merged, since i think there were a couple of things we had to finish up here, so its compatible with the latest version of the dev branch

### CODE REVIEW

**Comment by nezred** [comment]
also, even if, for the moment, the nullable parts are fine, maybe at some point if we have time we could take a closer look at that (like, what properties are nullable, and which arent). For the moment is fine though, and its not high priority in my opinion.

**Comment by nezred** [comment]
I was thinking, this part in the schema

```gql
  input MetricMetaDataInput {
    metric: String!
    unit: String
    scale: ScaleInput
    information: String
    tooltipSummary: String
  }
```

really should be 2 types, for adding and updating (updating, for instance, has all elements as nullables, in order to be able to select which parts we have to update or not), like how they are defined in the typescript types

**Comment by nezred** [comment]
there is also the fact that there exists the posibility of some things getting affected, because of the changes i will upload with the typescript types in the following commit (i dont think anything will break, because they arent any big structural changes, but idk)

**Review by leaandersenn — APPROVED** [review]

**Comment by nezred** [comment]
> I was thinking, this part in the schema

> ```gql
  input MetricMetaDataInput {
    metric: String!
    unit: String
    scale: ScaleInput
    information: String
    tooltipSummary: String
  }
```

> really should be 2 types, for adding and updating (updating, for instance, has all elements as nullables, in order to be able to select which parts we have to update or not), like how they are defined in the typescript types 

Ive changed this, for them to be 2 types, since its needed for the update mutation. Will put in next commit, when im done checking the last mutations

**Comment by sankeets** [comment]
> > I was thinking, this part in the schema
> > ```graphql
> >   input MetricMetaDataInput {
> >     metric: String!
> >     unit: String
> >     scale: ScaleInput
> >     information: String
> >     tooltipSummary: String
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > really should be 2 types, for adding and updating (updating, for instance, has all elements as nullables, in order to be able to select which parts we have to update or not), like how they are defined in the typescript types
> 
> Ive changed this, for them to be 2 types, since its needed for the update mutation. Will put in next commit, when im done checking the last mutations

is this ready to be merged?

**Pull request merged**
